#!/bin/bash

# 02614 - High-Performance Computing, January 2022

#BSUB -J par
#BSUB -oo par.out
#BSUB -eo par.err
#BSUB -q hpcintro
#BSUB -n 12
#BSUB -R "rusage[mem=2048]"
#BSUB -R "select[model == XeonE5_2650v4]"
#BSUB -W 60
#BSUB -R "span[hosts=1]"

#export OMP_PROC_BIND=close

module load studio

EXECUTABLE=poisson_j
EXECOPTS="150 4000 1e-2 0"

export OMP_WAIT_POLICY=active
CORES="4 8"

for C in $CORES
do
    export OMP_NUM_THREADS=$C
    collect -o $C.er ./$EXECUTABLE $EXECOPTS
done